name: WLED compile test

on:
    workflow_dispatch:
        inputs:
          input_test_data:
            description: 'Input data for test'
            required: true
            default: 'TESTDATAIN001'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: test
      run: |
        cd $GITHUB_WORKSPACE
        rm *.txt
        mkdir -p /tmp/WLEDtemp
        cd /tmp/WLEDtemp
        # echo '${{ github.event.inputs.input_test_data }}'
        echo -e '${{ github.event.inputs.input_test_data }}' >> testfile_${{ github.run_id }}.txt
    - name: Copy Files
      run: |
        cp /tmp/WLEDtemp/*.txt $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date_${{ github.run_id }}.txt
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BuildResults1
        path: |
          *.txt
        retention-days: 1
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BuildResults2
        path: custom_build.bin
        retention-days: 1
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add testfile_*.txt
        git commit -m "Commit build" testfile_*.txt
        git config pull.rebase false
        git pull
        git push origin main
          
